// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3FY6sHCo76Pvqdz8SLCwAJhlVnHcys_s',
    appId: '1:1054914907:web:052684d50e82a36d75427e',
    messagingSenderId: '1054914907',
    projectId: 'travel-planner-c69ed',
    authDomain: 'travel-planner-c69ed.firebaseapp.com',
    storageBucket: 'travel-planner-c69ed.firebasestorage.app',
    measurementId: 'G-KTSW031JFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrXIl90so1J5pSX2DW7Jm_JYBb-jESexk',
    appId: '1:1054914907:android:d72c900bbefb6d2575427e',
    messagingSenderId: '1054914907',
    projectId: 'travel-planner-c69ed',
    storageBucket: 'travel-planner-c69ed.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkD9AOC5TL8IMqxXvUHbHnBpwITs59jN8',
    appId: '1:1054914907:ios:08313776e92308c375427e',
    messagingSenderId: '1054914907',
    projectId: 'travel-planner-c69ed',
    storageBucket: 'travel-planner-c69ed.firebasestorage.app',
    iosBundleId: 'com.example.travelPlannerApp',
  );
}
